definitions:
  model.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  model.Order:
    properties:
      accrual:
        type: number
      number:
        type: string
      status:
        type: string
      uploaded_at:
        type: string
    type: object
  model.RegisterUser:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: login/password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: unauthorized
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      summary: Аутентификация пользователя
      tags:
      - user
  /api/user/orders:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Order'
            type: array
        "204":
          description: no content
          schema:
            type: string
        "401":
          description: unauthorized
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Список заказов пользователя
      tags:
      - orders
    post:
      consumes:
      - text/plain
      parameters:
      - description: Номер заказа (text/plain)
        in: body
        name: order
        required: true
        schema:
          type: string
      produces:
      - text/plain
      responses:
        "200":
          description: already uploaded by same user
          schema:
            type: string
        "202":
          description: accepted
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: unauthorized
          schema:
            type: string
        "409":
          description: conflict
          schema:
            type: string
        "422":
          description: unprocessable entity
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Загрузка номера заказа
      tags:
      - orders
  /api/user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: login/password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterUser'
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "409":
          description: conflict
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      summary: Регистрация пользователя
      tags:
      - user
swagger: "2.0"
